version: "3.7"

networks:
  back-tier:
    driver: bridge
    name: hero-backend

services:
  postgres-hero:
    hostname: postgres-hero
    image: postgres:11
    container_name: hero-postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./hero-db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hero
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=masterkey
    networks:
      - back-tier
